# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='first_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='next_to_move',
        ),
        migrations.RemoveField(
            model_name='game',
            name='second_player',
        ),
        migrations.RemoveField(
            model_name='move',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
    ]
